
spring:
  # 配置数据源
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingMall_sms?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: pass123456
    driver-class-name: com.mysql.jdbc.Driver
  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: coupon


mybatis-plus:
  # 配置sql.xml路径
  mapperLocations: classpath:mapper/**/*.xml
  # 主键自增
  global-config:
    db-config:
      id-type: auto
#定义端口
server:
  port: 7001

