# 配置数据源
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shoppingMall_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: pass123456
    driver-class-name: com.mysql.jdbc.Driver
  #nacos
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  application:
    name: member

mybatis-plus:
  # 配置sql.xml路径
  mapperLocations: classpath:mapper/**/*.xml
  # 主键自增
  global-config:
    db-config:
      id-type: auto

server:
  port: 8000